-- ========================================================================================================
-- SEQUENCES FOR UI INSERTS – ID auto-incremented by 1 for every new row
-- Run as the same user as your connection string (e.g. cinema). Safe to run multiple times.
-- Creates only missing sequences (ORA-00955 ignored); existing ones are left unchanged.
-- ========================================================================================================

BEGIN
   EXECUTE IMMEDIATE 'CREATE SEQUENCE USER_SEQ     START WITH 1 INCREMENT BY 1 NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   EXECUTE IMMEDIATE 'CREATE SEQUENCE PAYMENT_SEQ  START WITH 1 INCREMENT BY 1 NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   EXECUTE IMMEDIATE 'CREATE SEQUENCE MOVIE_SEQ    START WITH 1 INCREMENT BY 1 NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   EXECUTE IMMEDIATE 'CREATE SEQUENCE THEATRE_SEQ  START WITH 1 INCREMENT BY 1 NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   EXECUTE IMMEDIATE 'CREATE SEQUENCE HALL_SEQ     START WITH 1 INCREMENT BY 1 NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   EXECUTE IMMEDIATE 'CREATE SEQUENCE SHOW_SEQ     START WITH 1 INCREMENT BY 1 NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   EXECUTE IMMEDIATE 'CREATE SEQUENCE SEAT_SEQ     START WITH 1 INCREMENT BY 1 NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   EXECUTE IMMEDIATE 'CREATE SEQUENCE PRICE_SEQ    START WITH 1 INCREMENT BY 1 NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   EXECUTE IMMEDIATE 'CREATE SEQUENCE CANCEL_SEQ   START WITH 1 INCREMENT BY 1 NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   EXECUTE IMMEDIATE 'CREATE SEQUENCE BOOKING_SEQ  START WITH 1 INCREMENT BY 1 NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   EXECUTE IMMEDIATE 'CREATE SEQUENCE TICKET_SEQ   START WITH 1 INCREMENT BY 1 NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
